version: "3"
services:
  python_shell:
    image: python:latest
    container_name: python_shell_c
    ports:
      - 3000:3000
    volumes:
      - ./:/home/app
    working_dir: /home/app
    entrypoint: /bin/bash